#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x46502EF796917195 (mail@bernhard-voelker.de)
#
Name     : findutils
Version  : 4.9.0
Release  : 28
URL      : https://mirrors.kernel.org/gnu/findutils/findutils-4.9.0.tar.xz
Source0  : https://mirrors.kernel.org/gnu/findutils/findutils-4.9.0.tar.xz
Source1  : https://mirrors.kernel.org/gnu/findutils/findutils-4.9.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: findutils-bin = %{version}-%{release}
Requires: findutils-info = %{version}-%{release}
Requires: findutils-license = %{version}-%{release}
Requires: findutils-locales = %{version}-%{release}
Requires: findutils-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : dejagnu
BuildRequires : expect
BuildRequires : glibc-locale
BuildRequires : tcl

%description
This package contains the GNU find, xargs, and locate programs.  find
and xargs comply with POSIX 1003.2, as far as I know (with the
exception of the "+" modifier for the "-exec" action, which isn't
implemented yet).  They also support a large number of additional
options, some borrowed from Unix and some unique to GNU.

%package bin
Summary: bin components for the findutils package.
Group: Binaries
Requires: findutils-license = %{version}-%{release}

%description bin
bin components for the findutils package.


%package info
Summary: info components for the findutils package.
Group: Default

%description info
info components for the findutils package.


%package license
Summary: license components for the findutils package.
Group: Default

%description license
license components for the findutils package.


%package locales
Summary: locales components for the findutils package.
Group: Default

%description locales
locales components for the findutils package.


%package man
Summary: man components for the findutils package.
Group: Default

%description man
man components for the findutils package.


%prep
%setup -q -n findutils-4.9.0
cd %{_builddir}/findutils-4.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643917463
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1643917463
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/findutils
cp %{_builddir}/findutils-4.9.0/COPYING %{buildroot}/usr/share/package-licenses/findutils/31a3d460bb3c7d98845187c716a30db81c44b615
%make_install
%find_lang findutils
## Remove excluded files
rm -f %{buildroot}*/usr/bin/locate
rm -f %{buildroot}*/usr/bin/updatedb
rm -f %{buildroot}*/usr/libexec/bigram
rm -f %{buildroot}*/usr/libexec/code
rm -f %{buildroot}*/usr/libexec/frcode
rm -f %{buildroot}*/usr/share/man/man1/locate.1
rm -f %{buildroot}*/usr/share/man/man1/updatedb.1
rm -f %{buildroot}*/usr/share/man/man5/locatedb.5

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/find
/usr/bin/xargs

%files info
%defattr(0644,root,root,0755)
/usr/share/info/find-maint.info
/usr/share/info/find.info
/usr/share/info/find.info-1
/usr/share/info/find.info-2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/findutils/31a3d460bb3c7d98845187c716a30db81c44b615

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/find.1
/usr/share/man/man1/xargs.1

%files locales -f findutils.lang
%defattr(-,root,root,-)

