#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : findutils
Version  : 4.6.0
Release  : 16
URL      : http://ftp.gnu.org/gnu/findutils/findutils-4.6.0.tar.gz
Source0  : http://ftp.gnu.org/gnu/findutils/findutils-4.6.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.3 GPL-3.0 GPL-3.0+
Requires: findutils-bin
Requires: findutils-doc
Requires: findutils-locales
BuildRequires : dejagnu
BuildRequires : expect
BuildRequires : tcl

%description
This package contains the GNU find, xargs, and locate programs.  find
and xargs comply with POSIX 1003.2, as far as I know (with the
exception of the "+" modifier for the "-exec" action, which isn't
implemented yet).  They also support a large number of additional
options, some borrowed from Unix and some unique to GNU.

%package bin
Summary: bin components for the findutils package.
Group: Binaries

%description bin
bin components for the findutils package.


%package doc
Summary: doc components for the findutils package.
Group: Documentation

%description doc
doc components for the findutils package.


%package locales
Summary: locales components for the findutils package.
Group: Default

%description locales
locales components for the findutils package.


%prep
%setup -q -n findutils-4.6.0

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang findutils

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/find
/usr/bin/locate
/usr/bin/updatedb
/usr/bin/xargs
/usr/libexec/bigram
/usr/libexec/code
/usr/libexec/frcode

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*

%files locales -f findutils.lang 
%defattr(-,root,root,-)

